// Strictest practical lint configuration for every plugin in this repository.
//
// `tsc` and ESLint answer different questions: tsc asks "do the types line
// up", ESLint asks "is this a good idea". Both are turned up here — see
// tsconfig.base.json for the compiler half.
//
// The config itself is TypeScript, since this repository has no JavaScript
// sources; ESLint loads it through jiti.
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      // Never ours to lint.
      "**/dist/**",
      "**/node_modules/**",
      // Vendored UI source, copied from bb's component registry and
      // regenerated by `npx shadcn add`. It is still typechecked (see the
      // tsconfig include lists) but linting it only produces churn that the
      // next regeneration discards. Note that disableTypeChecked would not be
      // enough: it silences the type-aware rules and leaves the stylistic ones
      // reporting.
      "**/components/ui/**",
      "**/hooks/**",
      "**/lib/**",
    ],
  },

  eslint.configs.recommended,

  // strictTypeChecked is the strongest preset typescript-eslint ships: it needs
  // real type information and catches the things a syntax-only linter cannot,
  // like awaiting a non-promise or a template literal that stringifies an
  // object. stylisticTypeChecked adds the consistency rules on top.
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        // Resolves each file against whichever plugin tsconfig owns it, which
        // is what makes type-aware rules work across a workspace.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // The SDK hands back plenty of `unknown`, and narrowing it with a cast at
      // a validated boundary is the intended pattern rather than a mistake.
      "@typescript-eslint/no-unsafe-assignment": "off",
      // Fine for `${count}` and `${version}`; still errors on objects.
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
    },
  },

  {
    // Tooling config, not shipped code, and checked against typescript-eslint's
    // own loosely typed config helpers — type-aware rules report on their
    // internals rather than on anything written here. Must come after the
    // presets above: flat config is order-dependent, so an earlier placement
    // would simply be re-enabled by them.
    files: ["eslint.config.ts"],
    ...tseslint.configs.disableTypeChecked,
  },

  {
    // A plugin factory is an await-capable extension point: the host awaits it
    // and so do the tests, and read-aloud's genuinely awaits its settings.
    // Declaring it async is part of that contract rather than an oversight, so
    // do not demand an await inside the ones that happen not to need one yet.
    files: ["**/server.ts"],
    rules: {
      "@typescript-eslint/require-await": "off",
    },
  },

  {
    // Tests legitimately reach for casts and non-null assertions to build
    // fixtures; that is fixture-shaping, not a type hole in shipped code.
    files: ["**/*.test.ts", "**/*.test.tsx"],
    rules: {
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      // Fake SDK methods must return promises to match the real signatures,
      // and `async` is the clearest way to say so even with nothing to await.
      "@typescript-eslint/require-await": "off",
    },
  },
);
